<?xml version="1.0" encoding="utf-8"?>
<section xmlns="http://docbook.org/ns/docbook" version="5.0" xml:id="zend.exception.using"><info><title>Koriscenje izuzetaka</title></info>

    

    <para>
        All exceptions thrown by Zend Framework classes should throw
        an exception that derives from the base class Zend_Exception.
    </para>

    <example xml:id="zend.exception.using.example"><info><title>Example of catching an exception</title></info>
        
        <programlisting role="php"><![CDATA[<?php

try {
    Zend_Loader::loadClass('nonexistantclass');
} catch (Zend_Exception $e) {
    echo "Caught exception: " . get_class($e) . "\n";
    echo "Message: " . $e->getMessage() . "\n";
    // other code to recover from the failure.
}

?>]]></programlisting>
    </example>

    <para>
        See the documentation for each respective Zend Framework
        component for more specific information on which methods
        throw exceptions, the circumstances for the exceptions,
        and which exception classes derive from Zend_Exception.
    </para>

</section>
