<?xml version="1.0" encoding="utf-8"?>
<section xmlns="http://docbook.org/ns/docbook" version="5.0" xml:id="zend.exception.using"><info><title>Používanie výnimiek</title></info>
    

    <para>
        Všetky výnimky generované triedami Zend Framework mali by byť
        odvodené od základnej triedy Zend_Exception.
    </para>

    <example xml:id="zend.exception.using.example"><info><title>Príklad odchytenia výnimky</title></info>
        
        <programlisting role="php"><![CDATA[<?php

try {
    Zend_Loader::loadClass('nonexistantclass');
} catch (Zend_Exception $e) {
    echo "Caught exception: " . get_class($e) . "\n";
    echo "Message: " . $e->getMessage() . "\n";
    // pokračovanie kódu pre zotavenie sa z chyby
}

?>]]></programlisting>
    </example>

    <para>
        Ku každej časti Zend Framework sú v dokumentácii uvedené
        informácie o metódach ktoré používajú výnimky, informácie
        o dôvodoch generovania výnimiek a názvy tried ktoré sú
        odvodené od Zend_Exception.
    </para>

</section>
